const WORDS_18PLUS = [
  { word: "Szexuális perverzió", mode: "Magyarázd el!", points: 2 },
  { word: "Szexuális perverzió", mode: "Szájról olvasás!", points: 2 },
  { word: "Tantrikus szex", mode: "Magyarázd el!", points: 3 },
  { word: "Tantrikus szex", mode: "Szájról olvasás!", points: 2 },
  { word: "Többszörös orgazmus", mode: "Mutasd meg!", points: 2 },
  { word: "Többszörös orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "Kézimunka", mode: "Magyarázd el!", points: 1 },
  { word: "Kézimunka", mode: "Szájról olvasás!", points: 2 },
  { word: "Pénisz alakú vibrátor", mode: "Rajzold le!", points: 1 },
  { word: "Pénisz alakú vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "Mellbimbó piercing", mode: "Rajzold le!", points: 1 },
  { word: "Mellbimbó piercing", mode: "Szájról olvasás!", points: 2 },
  { word: "Péniszgyűrű", mode: "Rajzold le!", points: 1 },
  { word: "Péniszgyűrű", mode: "Szájról olvasás!", points: 2 },
  { word: "Síkosító folyadék", mode: "Magyarázd el!", points: 1 },
  { word: "Síkosító folyadék", mode: "Szájról olvasás!", points: 2 },
  { word: "Asztaltánc", mode: "Mutasd meg!", points: 2 },
  { word: "Asztaltánc", mode: "Szájról olvasás!", points: 2 },
  { word: "miniszoknya", mode: "Mutasd meg!", points: 3 },
  { word: "miniszoknya", mode: "Szájról olvasás!", points: 2 },
  { word: "kebelcsoda", mode: "Rajzold le!", points: 3 },
  { word: "kebelcsoda", mode: "Szájról olvasás!", points: 2 },
  { word: "erogén dudor", mode: "Rajzold le!", points: 3 },
  { word: "erogén dudor", mode: "Szájról olvasás!", points: 2 },
  { word: "szexbomba", mode: "Rajzold le!", points: 2 },
  { word: "szexbomba", mode: "Szájról olvasás!", points: 2 },
  { word: "mellnagyobbítás", mode: "Rajzold le!", points: 2 },
  { word: "mellnagyobbítás", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelmi fészek", mode: "Rajzold le!", points: 3 },
  { word: "szerelmi fészek", mode: "Szájról olvasás!", points: 2 },
  { word: "börtön szex", mode: "Mutasd meg!", points: 2 },
  { word: "börtön szex", mode: "Szájról olvasás!", points: 2 },
  { word: "hermafrodita", mode: "Magyarázd el!", points: 2 },
  { word: "hermafrodita", mode: "Szájról olvasás!", points: 2 },
  { word: "herezacskó", mode: "Rajzold le!", points: 1 },
  { word: "herezacskó", mode: "Szájról olvasás!", points: 2 },
  { word: "pásztoróra", mode: "Rajzold le!", points: 3 },
  { word: "pásztoróra", mode: "Szájról olvasás!", points: 2 },
  { word: "homoszexualitás", mode: "Magyarázd el!", points: 1 },
  { word: "homoszexualitás", mode: "Szájról olvasás!", points: 2 },
  { word: "szexuális fetisizmus áramütéssel", mode: "Magyarázd el!", points: 3 },
  { word: "szexuális fetisizmus áramütéssel", mode: "Szájról olvasás!", points: 2 },
  { word: "megszakított közösülés", mode: "Magyarázd el!", points: 2 },
  { word: "megszakított közösülés", mode: "Szájról olvasás!", points: 2 },
  { word: "szexistennő", mode: "Magyarázd el!", points: 1 },
  { word: "szexistennő", mode: "Szájról olvasás!", points: 2 },
  { word: "hüvelyváladék", mode: "Magyarázd el!", points: 2 },
  { word: "hüvelyváladék", mode: "Szájról olvasás!", points: 2 },
  { word: "pornófilm", mode: "Mutasd meg!", points: 2 },
  { word: "pornófilm", mode: "Szájról olvasás!", points: 2 },
  { word: "pajzán gondolatok", mode: "Magyarázd el!", points: 2 },
  { word: "pajzán gondolatok", mode: "Szájról olvasás!", points: 2 },
  { word: "kiveri a farkát", mode: "Mutasd meg!", points: 1 },
  { word: "kiveri a farkát", mode: "Szájról olvasás!", points: 2 },
  { word: "szex olaj", mode: "Mutasd meg!", points: 2 },
  { word: "szex olaj", mode: "Szájról olvasás!", points: 2 },
  { word: "extázis", mode: "Magyarázd el!", points: 3 },
  { word: "extázis", mode: "Szájról olvasás!", points: 2 },
  { word: "rúdtáncosnő", mode: "Mutasd meg!", points: 1 },
  { word: "rúdtáncosnő", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelemkrém", mode: "Mutasd meg!", points: 3 },
  { word: "szerelemkrém", mode: "Szájról olvasás!", points: 2 },
  { word: "trágárság", mode: "Magyarázd el!", points: 2 },
  { word: "trágárság", mode: "Szájról olvasás!", points: 2 },
  { word: "durva szex", mode: "Magyarázd el!", points: 1 },
  { word: "durva szex", mode: "Szájról olvasás!", points: 2 },
  { word: "mellbimbó csipesz", mode: "Rajzold le!", points: 3 },
  { word: "mellbimbó csipesz", mode: "Szájról olvasás!", points: 2 },
  { word: "virtuális gumibaba", mode: "Magyarázd el!", points: 3 },
  { word: "virtuális gumibaba", mode: "Szájról olvasás!", points: 2 },
  { word: "szemérmes", mode: "Magyarázd el!", points: 2 },
  { word: "szemérmes", mode: "Szájról olvasás!", points: 2 },
  { word: "milf", mode: "Magyarázd el!", points: 1 },
  { word: "milf", mode: "Szájról olvasás!", points: 2 },
  { word: "nászéjszaka", mode: "Mutasd meg!", points: 3 },
  { word: "nászéjszaka", mode: "Szájról olvasás!", points: 2 },
  { word: "péniszpumpa", mode: "Rajzold le!", points: 3 },
  { word: "péniszpumpa", mode: "Szájról olvasás!", points: 2 },
  { word: "impotencia", mode: "Mutasd meg!", points: 1 },
  { word: "impotencia", mode: "Szájról olvasás!", points: 2 },
  { word: "libidó", mode: "Magyarázd el!", points: 2 },
  { word: "libidó", mode: "Szájról olvasás!", points: 2 },
  { word: "hímvessző", mode: "Rajzold le!", points: 1 },
  { word: "hímvessző", mode: "Szájról olvasás!", points: 2 },
  { word: "casanova", mode: "Magyarázd el!", points: 2 },
  { word: "casanova", mode: "Szájról olvasás!", points: 2 },
  { word: "háromszögre gyantázott punci", mode: "Rajzold le!", points: 1 },
  { word: "háromszögre gyantázott punci", mode: "Szájról olvasás!", points: 2 },
  { word: "csukló és boka bilincs", mode: "Rajzold le!", points: 2 },
  { word: "csukló és boka bilincs", mode: "Szájról olvasás!", points: 2 },
  { word: "meglovaglás", mode: "Mutasd meg!", points: 1 },
  { word: "meglovaglás", mode: "Szájról olvasás!", points: 2 },
  { word: "pornó színész", mode: "Magyarázd el!", points: 1 },
  { word: "pornó színész", mode: "Szájról olvasás!", points: 2 },
  { word: "felfújható gumiállat", mode: "Mutasd meg!", points: 3 },
  { word: "felfújható gumiállat", mode: "Szájról olvasás!", points: 2 },
  { word: "peep show", mode: "Mutasd meg!", points: 2 },
  { word: "peep show", mode: "Szájról olvasás!", points: 2 },
  { word: "franciázás", mode: "Rajzold le!", points: 2 },
  { word: "franciázás", mode: "Szájról olvasás!", points: 2 },
  { word: "erekció", mode: "Rajzold le!", points: 1 },
  { word: "erekció", mode: "Szájról olvasás!", points: 2 },
  { word: "gruppen szex", mode: "Mutasd meg!", points: 2 },
  { word: "gruppen szex", mode: "Szájról olvasás!", points: 2 },
  { word: "fogamzásgátló tabletta", mode: "Magyarázd el!", points: 1 },
  { word: "fogamzásgátló tabletta", mode: "Szájról olvasás!", points: 2 },
  { word: "golyószopás", mode: "Mutasd meg!", points: 1 },
  { word: "golyószopás", mode: "Szájról olvasás!", points: 2 },
  { word: "dupla behatolás", mode: "Mutasd meg!", points: 1 },
  { word: "dupla behatolás", mode: "Szájról olvasás!", points: 2 },
  { word: "kurtizán", mode: "Magyarázd el!", points: 2 },
  { word: "kurtizán", mode: "Szájról olvasás!", points: 2 },
  { word: "felhelyezhető vibrátor", mode: "Magyarázd el!", points: 2 },
  { word: "felhelyezhető vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "rúdvibrátor", mode: "Rajzold le!", points: 2 },
  { word: "rúdvibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "dildó", mode: "Rajzold le!", points: 1 },
  { word: "dildó", mode: "Szájról olvasás!", points: 2 },
  { word: "transzszexuális", mode: "Magyarázd el!", points: 1 },
  { word: "transzszexuális", mode: "Szájról olvasás!", points: 2 },
  { word: "megkötözős szex", mode: "Mutasd meg!", points: 2 },
  { word: "megkötözős szex", mode: "Szájról olvasás!", points: 2 },
  { word: "érzékiség", mode: "Magyarázd el!", points: 1 },
  { word: "érzékiség", mode: "Szájról olvasás!", points: 2 },
  { word: "előjáték", mode: "Magyarázd el!", points: 1 },
  { word: "előjáték", mode: "Szájról olvasás!", points: 2 },
  { word: "kéjcsepp", mode: "Rajzold le!", points: 3 },
  { word: "kéjcsepp", mode: "Szájról olvasás!", points: 2 },
  { word: "egymáshoz simulás", mode: "Mutasd meg!", points: 3 },
  { word: "egymáshoz simulás", mode: "Szájról olvasás!", points: 2 },
  { word: "szexbaba", mode: "Rajzold le!", points: 1 },
  { word: "szexbaba", mode: "Szájról olvasás!", points: 2 },
  { word: "édes hármas", mode: "Magyarázd el!", points: 1 },
  { word: "édes hármas", mode: "Szájról olvasás!", points: 2 },
  { word: "buja", mode: "Magyarázd el!", points: 2 },
  { word: "buja", mode: "Szájról olvasás!", points: 2 },
  { word: "nyuszi vibrátor", mode: "Rajzold le!", points: 2 },
  { word: "nyuszi vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "harisnya imádó", mode: "Magyarázd el!", points: 1 },
  { word: "harisnya imádó", mode: "Szájról olvasás!", points: 2 },
  { word: "vibráló szivacs", mode: "Magyarázd el!", points: 2 },
  { word: "vibráló szivacs", mode: "Szájról olvasás!", points: 2 },
  { word: "csikló masszázs", mode: "Mutasd meg!", points: 2 },
  { word: "csikló masszázs", mode: "Szájról olvasás!", points: 2 },
  { word: "nyelvgyakorlat", mode: "Magyarázd el!", points: 2 },
  { word: "nyelvgyakorlat", mode: "Szájról olvasás!", points: 2 },
  { word: "szexfüggő", mode: "Mutasd meg!", points: 3 },
  { word: "szexfüggő", mode: "Szájról olvasás!", points: 2 },
  { word: "zselés vibrátor", mode: "Rajzold le!", points: 3 },
  { word: "zselés vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "clitoris izgató vibrátor", mode: "Rajzold le!", points: 3 },
  { word: "clitoris izgató vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "mellbimbó udvar", mode: "Rajzold le!", points: 1 },
  { word: "mellbimbó udvar", mode: "Szájról olvasás!", points: 2 },
  { word: "cyber szex", mode: "Magyarázd el!", points: 2 },
  { word: "cyber szex", mode: "Szájról olvasás!", points: 2 },
  { word: "cirógatás", mode: "Mutasd meg!", points: 2 },
  { word: "cirógatás", mode: "Szájról olvasás!", points: 2 },
  { word: "merevedési zavar", mode: "Mutasd meg!", points: 1 },
  { word: "merevedési zavar", mode: "Szájról olvasás!", points: 2 },
  { word: "szexfüggőség", mode: "Magyarázd el!", points: 1 },
  { word: "szexfüggőség", mode: "Szájról olvasás!", points: 2 },
  { word: "nyalás", mode: "Mutasd meg!", points: 1 },
  { word: "nyalás", mode: "Szájról olvasás!", points: 2 },
  { word: "feromon", mode: "Magyarázd el!", points: 2 },
  { word: "feromon", mode: "Szájról olvasás!", points: 2 },
  { word: "sikosító gél", mode: "Rajzold le!", points: 2 },
  { word: "sikosító gél", mode: "Szájról olvasás!", points: 2 },
  { word: "homoszexuális", mode: "Magyarázd el!", points: 1 },
  { word: "homoszexuális", mode: "Szájról olvasás!", points: 2 },
  { word: "orvos szex", mode: "Magyarázd el!", points: 1 },
  { word: "orvos szex", mode: "Szájról olvasás!", points: 2 },
  { word: "vibrátoros száj", mode: "Mutasd meg!", points: 3 },
  { word: "vibrátoros száj", mode: "Szájról olvasás!", points: 2 },
  { word: "csikló izgatása", mode: "Mutasd meg!", points: 2 },
  { word: "csikló izgatása", mode: "Szájról olvasás!", points: 2 },
  { word: "kézügyesség", mode: "Magyarázd el!", points: 2 },
  { word: "kézügyesség", mode: "Szájról olvasás!", points: 2 },
  { word: "potencia zavar", mode: "Magyarázd el!", points: 1 },
  { word: "potencia zavar", mode: "Szájról olvasás!", points: 2 },
  { word: "latex ruha", mode: "Magyarázd el!", points: 1 },
  { word: "latex ruha", mode: "Szájról olvasás!", points: 2 },
  { word: "spriccel", mode: "Mutasd meg!", points: 1 },
  { word: "spriccel", mode: "Szájról olvasás!", points: 2 },
  { word: "aktmodell", mode: "Mutasd meg!", points: 2 },
  { word: "aktmodell", mode: "Szájról olvasás!", points: 2 },
  { word: "szexi jelmez", mode: "Mutasd meg!", points: 2 },
  { word: "szexi jelmez", mode: "Szájról olvasás!", points: 2 },
  { word: "péniszes mellbilincs", mode: "Rajzold le!", points: 3 },
  { word: "péniszes mellbilincs", mode: "Szájról olvasás!", points: 2 },
  { word: "spermabank", mode: "Rajzold le!", points: 1 },
  { word: "spermabank", mode: "Szájról olvasás!", points: 2 },
  { word: "swinger party", mode: "Magyarázd el!", points: 1 },
  { word: "swinger party", mode: "Szájról olvasás!", points: 2 },
  { word: "autós szex", mode: "Mutasd meg!", points: 1 },
  { word: "autós szex", mode: "Szájról olvasás!", points: 2 },
  { word: "leszbikus", mode: "Magyarázd el!", points: 1 },
  { word: "leszbikus", mode: "Szájról olvasás!", points: 2 },
  { word: "szex shop", mode: "Magyarázd el!", points: 1 },
  { word: "szex shop", mode: "Szájról olvasás!", points: 2 },
  { word: "utójáték", mode: "Magyarázd el!", points: 2 },
  { word: "utójáték", mode: "Szájról olvasás!", points: 2 },
  { word: "fallosz", mode: "Magyarázd el!", points: 2 },
  { word: "fallosz", mode: "Szájról olvasás!", points: 2 },
  { word: "üzletszerű kéjelgés", mode: "Magyarázd el!", points: 3 },
  { word: "üzletszerű kéjelgés", mode: "Szájról olvasás!", points: 2 },
  { word: "szopás", mode: "Mutasd meg!", points: 1 },
  { word: "szopás", mode: "Szájról olvasás!", points: 2 },
  { word: "pénisz hosszabbító", mode: "Rajzold le!", points: 2 },
  { word: "pénisz hosszabbító", mode: "Szájról olvasás!", points: 2 },
  { word: "fülbe nyalás", mode: "Mutasd meg!", points: 1 },
  { word: "fülbe nyalás", mode: "Szájról olvasás!", points: 2 },
  { word: "szex hinta", mode: "Rajzold le!", points: 2 },
  { word: "szex hinta", mode: "Szájról olvasás!", points: 2 },
  { word: "intim piercing", mode: "Rajzold le!", points: 2 },
  { word: "intim piercing", mode: "Szájról olvasás!", points: 2 },
  { word: "erényöv", mode: "Mutasd meg!", points: 2 },
  { word: "erényöv", mode: "Szájról olvasás!", points: 2 },
  { word: "nemi aktus", mode: "Mutasd meg!", points: 3 },
  { word: "nemi aktus", mode: "Szájról olvasás!", points: 2 },
  { word: "aktfotós naptár", mode: "Rajzold le!", points: 2 },
  { word: "aktfotós naptár", mode: "Szájról olvasás!", points: 2 },
  { word: "begerjeszt", mode: "Magyarázd el!", points: 1 },
  { word: "begerjeszt", mode: "Szájról olvasás!", points: 2 },
  { word: "vakrandi", mode: "Magyarázd el!", points: 1 },
  { word: "vakrandi", mode: "Szájról olvasás!", points: 2 },
  { word: "kasztráció", mode: "Magyarázd el!", points: 1 },
  { word: "kasztráció", mode: "Szájról olvasás!", points: 2 },
  { word: "transzvesztita show", mode: "Mutasd meg!", points: 2 },
  { word: "transzvesztita show", mode: "Szájról olvasás!", points: 2 },
  { word: "bordélyház", mode: "Magyarázd el!", points: 1 },
  { word: "bordélyház", mode: "Szájról olvasás!", points: 2 },
  { word: "maszturbálás", mode: "Mutasd meg!", points: 1 },
  { word: "maszturbálás", mode: "Szájról olvasás!", points: 2 },
  { word: "szex a fürdőkádban", mode: "Mutasd meg!", points: 2 },
  { word: "szex a fürdőkádban", mode: "Szájról olvasás!", points: 2 },
  { word: "összedörzsölés", mode: "Mutasd meg!", points: 2 },
  { word: "összedörzsölés", mode: "Szájról olvasás!", points: 2 },
  { word: "internetes szex", mode: "Magyarázd el!", points: 1 },
  { word: "internetes szex", mode: "Szájról olvasás!", points: 2 },
  { word: "szexuális játékszer", mode: "Magyarázd el!", points: 2 },
  { word: "szexuális játékszer", mode: "Szájról olvasás!", points: 2 },
  { word: "latex harisnya", mode: "Mutasd meg!", points: 2 },
  { word: "latex harisnya", mode: "Szájról olvasás!", points: 2 },
  { word: "seggbedugás", mode: "Mutasd meg!", points: 1 },
  { word: "seggbedugás", mode: "Szájról olvasás!", points: 2 },
  { word: "szenvedélyes", mode: "Magyarázd el!", points: 1 },
  { word: "szenvedélyes", mode: "Szájról olvasás!", points: 2 },
  { word: "szüzesség", mode: "Rajzold le!", points: 2 },
  { word: "szüzesség", mode: "Szájról olvasás!", points: 2 },
  { word: "izgató", mode: "Mutasd meg!", points: 1 },
  { word: "izgató", mode: "Szájról olvasás!", points: 2 },
  { word: "intimzuhany", mode: "Rajzold le!", points: 3 },
  { word: "intimzuhany", mode: "Szájról olvasás!", points: 2 },
  { word: "testfestés", mode: "Mutasd meg!", points: 2 },
  { word: "testfestés", mode: "Szájról olvasás!", points: 2 },
  { word: "láncos mellbimbócsipesz", mode: "Rajzold le!", points: 3 },
  { word: "láncos mellbimbócsipesz", mode: "Szájról olvasás!", points: 2 },
  { word: "bódult", mode: "Magyarázd el!", points: 1 },
  { word: "bódult", mode: "Szájról olvasás!", points: 2 },
  { word: "hüvelyi orgazmus", mode: "Mutasd meg!", points: 3 },
  { word: "hüvelyi orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "partner csere", mode: "Mutasd meg!", points: 2 },
  { word: "partner csere", mode: "Szájról olvasás!", points: 2 },
  { word: "maszturbáció", mode: "Mutasd meg!", points: 1 },
  { word: "maszturbáció", mode: "Szájról olvasás!", points: 2 },
  { word: "szex", mode: "Mutasd meg!", points: 1 },
  { word: "szex", mode: "Szájról olvasás!", points: 2 },
  { word: "anál sikosító", mode: "Magyarázd el!", points: 2 },
  { word: "anál sikosító", mode: "Szájról olvasás!", points: 2 },
  { word: "szeméremajkak", mode: "Mutasd meg!", points: 3 },
  { word: "szeméremajkak", mode: "Szájról olvasás!", points: 2 },
  { word: "szülinapi szex", mode: "Mutasd meg!", points: 3 },
  { word: "szülinapi szex", mode: "Szájról olvasás!", points: 2 },
  { word: "fantáziálás", mode: "Magyarázd el!", points: 1 },
  { word: "fantáziálás", mode: "Szájról olvasás!", points: 2 },
  { word: "ejakuláció", mode: "Mutasd meg!", points: 2 },
  { word: "ejakuláció", mode: "Szájról olvasás!", points: 2 },
  { word: "kék tabletta", mode: "Magyarázd el!", points: 2 },
  { word: "kék tabletta", mode: "Szájról olvasás!", points: 2 },
  { word: "szex játékok", mode: "Magyarázd el!", points: 1 },
  { word: "szex játékok", mode: "Szájról olvasás!", points: 2 },
  { word: "kézimunka", mode: "Magyarázd el!", points: 1 },
  { word: "kézimunka", mode: "Szájról olvasás!", points: 2 },
  { word: "pénisz alakú vibrátor", mode: "Rajzold le!", points: 1 },
  { word: "pénisz alakú vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "tantrikus szex", mode: "Magyarázd el!", points: 3 },
  { word: "tantrikus szex", mode: "Szájról olvasás!", points: 2 },
  { word: "sikosító folyadék", mode: "Magyarázd el!", points: 1 },
  { word: "sikosító folyadék", mode: "Szájról olvasás!", points: 2 },
  { word: "péniszgyűrű", mode: "Rajzold le!", points: 2 },
  { word: "péniszgyűrű", mode: "Szájról olvasás!", points: 2 },
  { word: "mellbimbó piercing", mode: "Rajzold le!", points: 2 },
  { word: "mellbimbó piercing", mode: "Szájról olvasás!", points: 2 },
  { word: "többszörös orgazmus", mode: "Mutasd meg!", points: 2 },
  { word: "többszörös orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "kibékülős szex", mode: "Magyarázd el!", points: 1 },
  { word: "kibékülős szex", mode: "Szájról olvasás!", points: 2 },
  { word: "golyós szájpecek", mode: "Rajzold le!", points: 2 },
  { word: "golyós szájpecek", mode: "Szájról olvasás!", points: 2 },
  { word: "erogén zóna", mode: "Rajzold le!", points: 2 },
  { word: "erogén zóna", mode: "Szájról olvasás!", points: 2 },
  { word: "felcsatolható vibrátor", mode: "Mutasd meg!", points: 2 },
  { word: "felcsatolható vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "üveg spirál", mode: "Magyarázd el!", points: 2 },
  { word: "üveg spirál", mode: "Szájról olvasás!", points: 2 },
  { word: "tanga", mode: "Rajzold le!", points: 1 },
  { word: "tanga", mode: "Szájról olvasás!", points: 2 },
  { word: "vagina", mode: "Rajzold le!", points: 1 },
  { word: "vagina", mode: "Szájról olvasás!", points: 2 },
  { word: "baszás", mode: "Mutasd meg!", points: 1 },
  { word: "baszás", mode: "Szájról olvasás!", points: 2 },
  { word: "pucsítás", mode: "Mutasd meg!", points: 1 },
  { word: "pucsítás", mode: "Szájról olvasás!", points: 2 },
  { word: "a gyönyör bugyrai", mode: "Magyarázd el!", points: 3 },
  { word: "a gyönyör bugyrai", mode: "Szájról olvasás!", points: 2 },
  { word: "szex a szabadban", mode: "Magyarázd el!", points: 2 },
  { word: "szex a szabadban", mode: "Szájról olvasás!", points: 2 },
  { word: "telefon szex", mode: "Mutasd meg!", points: 1 },
  { word: "telefon szex", mode: "Szájról olvasás!", points: 2 },
  { word: "szemmaszk", mode: "Rajzold le!", points: 2 },
  { word: "szemmaszk", mode: "Szájról olvasás!", points: 2 },
  { word: "misszionárius póz", mode: "Mutasd meg!", points: 1 },
  { word: "misszionárius póz", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelmeskedés", mode: "Mutasd meg!", points: 1 },
  { word: "szerelmeskedés", mode: "Szájról olvasás!", points: 2 },
  { word: "mocskos dolgok suttogása szex közben", mode: "Magyarázd el!", points: 1 },
  { word: "mocskos dolgok suttogása szex közben", mode: "Szájról olvasás!", points: 2 },
  { word: "szexis fehérnemű", mode: "Mutasd meg!", points: 3 },
  { word: "szexis fehérnemű", mode: "Szájról olvasás!", points: 2 },
  { word: "lábimádó", mode: "Rajzold le!", points: 2 },
  { word: "lábimádó", mode: "Szájról olvasás!", points: 2 },
  { word: "vagina izgatás", mode: "Mutasd meg!", points: 2 },
  { word: "vagina izgatás", mode: "Szájról olvasás!", points: 2 },
  { word: "mellgyűrű", mode: "Rajzold le!", points: 2 },
  { word: "mellgyűrű", mode: "Szájról olvasás!", points: 2 },
  { word: "behatolás", mode: "Mutasd meg!", points: 1 },
  { word: "behatolás", mode: "Szájról olvasás!", points: 2 },
  { word: "prosztata masszázs", mode: "Magyarázd el!", points: 2 },
  { word: "prosztata masszázs", mode: "Szájról olvasás!", points: 2 },
  { word: "terhességi teszt", mode: "Magyarázd el!", points: 1 },
  { word: "terhességi teszt", mode: "Szájról olvasás!", points: 2 },
  { word: "péniszmasszázs", mode: "Mutasd meg!", points: 2 },
  { word: "péniszmasszázs", mode: "Szájról olvasás!", points: 2 },
  { word: "ízesített óvszer", mode: "Mutasd meg!", points: 2 },
  { word: "ízesített óvszer", mode: "Szájról olvasás!", points: 2 },
  { word: "titkárnő szex", mode: "Magyarázd el!", points: 2 },
  { word: "titkárnő szex", mode: "Szájról olvasás!", points: 2 },
  { word: "69-es póz", mode: "Mutasd meg!", points: 1 },
  { word: "69-es póz", mode: "Szájról olvasás!", points: 2 },
  { word: "gigantikus pénisz", mode: "Rajzold le!", points: 2 },
  { word: "gigantikus pénisz", mode: "Szájról olvasás!", points: 2 },
  { word: "hüvelytágító", mode: "Mutasd meg!", points: 3 },
  { word: "hüvelytágító", mode: "Szájról olvasás!", points: 2 },
  { word: "borotvált punci", mode: "Rajzold le!", points: 1 },
  { word: "borotvált punci", mode: "Szájról olvasás!", points: 2 },
  { word: "utcai prosti", mode: "Magyarázd el!", points: 1 },
  { word: "utcai prosti", mode: "Szájról olvasás!", points: 2 },
  { word: "fétis ruha (bőr, latex)", mode: "Magyarázd el!", points: 2 },
  { word: "fétis ruha (bőr, latex)", mode: "Szájról olvasás!", points: 2 },
  { word: "gyönyör", mode: "Magyarázd el!", points: 1 },
  { word: "gyönyör", mode: "Szájról olvasás!", points: 2 },
  { word: "intim tetkó", mode: "Rajzold le!", points: 2 },
  { word: "intim tetkó", mode: "Szájról olvasás!", points: 2 },
  { word: "szexpartner", mode: "Magyarázd el!", points: 1 },
  { word: "szexpartner", mode: "Szájról olvasás!", points: 2 },
  { word: "csúcspont", mode: "Rajzold le!", points: 2 },
  { word: "csúcspont", mode: "Szájról olvasás!", points: 2 },
  { word: "egyéjszakás kaland", mode: "Magyarázd el!", points: 1 },
  { word: "egyéjszakás kaland", mode: "Szájról olvasás!", points: 2 },
  { word: "házi pornó", mode: "Magyarázd el!", points: 1 },
  { word: "házi pornó", mode: "Szájról olvasás!", points: 2 },
  { word: "csiklóizgatós péniszgyűrű", mode: "Rajzold le!", points: 3 },
  { word: "csiklóizgatós péniszgyűrű", mode: "Szájról olvasás!", points: 2 },
  { word: "felláció", mode: "Magyarázd el!", points: 2 },
  { word: "felláció", mode: "Szájról olvasás!", points: 2 },
  { word: "szeretkezés", mode: "Mutasd meg!", points: 1 },
  { word: "szeretkezés", mode: "Szájról olvasás!", points: 2 },
  { word: "here", mode: "Rajzold le!", points: 1 },
  { word: "here", mode: "Szájról olvasás!", points: 2 },
  { word: "szex pózok", mode: "Mutasd meg!", points: 2 },
  { word: "szex pózok", mode: "Szájról olvasás!", points: 2 },
  { word: "testnyílás", mode: "Rajzold le!", points: 2 },
  { word: "testnyílás", mode: "Szájról olvasás!", points: 2 },
  { word: "ánusz tágító", mode: "Mutasd meg!", points: 3 },
  { word: "ánusz tágító", mode: "Szájról olvasás!", points: 2 },
  { word: "pettingelés", mode: "Mutasd meg!", points: 3 },
  { word: "pettingelés", mode: "Szájról olvasás!", points: 2 },
  { word: "szado-mazo szex", mode: "Mutasd meg!", points: 2 },
  { word: "szado-mazo szex", mode: "Szájról olvasás!", points: 2 },
  { word: "aszexualitás", mode: "Magyarázd el!", points: 1 },
  { word: "aszexualitás", mode: "Szájról olvasás!", points: 2 },
  { word: "prosztata vibrátor", mode: "Mutasd meg!", points: 3 },
  { word: "prosztata vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "dupla pénisz vibrátor", mode: "Rajzold le!", points: 2 },
  { word: "dupla pénisz vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "anális szex", mode: "Rajzold le!", points: 1 },
  { word: "anális szex", mode: "Szájról olvasás!", points: 2 },
  { word: "leszbi csajok", mode: "Magyarázd el!", points: 1 },
  { word: "leszbi csajok", mode: "Szájról olvasás!", points: 2 },
  { word: "szex a zuhany alatt", mode: "Mutasd meg!", points: 1 },
  { word: "szex a zuhany alatt", mode: "Szájról olvasás!", points: 2 },
  { word: "vibrátor", mode: "Rajzold le!", points: 1 },
  { word: "vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "arcra élvezés", mode: "Mutasd meg!", points: 1 },
  { word: "arcra élvezés", mode: "Szájról olvasás!", points: 2 },
  { word: "biszexualitás", mode: "Magyarázd el!", points: 1 },
  { word: "biszexualitás", mode: "Szájról olvasás!", points: 2 },
  { word: "gyengéd szex", mode: "Magyarázd el!", points: 1 },
  { word: "gyengéd szex", mode: "Szájról olvasás!", points: 2 },
  { word: "párcsere", mode: "Magyarázd el!", points: 1 },
  { word: "párcsere", mode: "Szájról olvasás!", points: 2 },
  { word: "anál gyöngyök", mode: "Rajzold le!", points: 2 },
  { word: "anál gyöngyök", mode: "Szájról olvasás!", points: 2 },
  { word: "kéjsóvár", mode: "Magyarázd el!", points: 3 },
  { word: "kéjsóvár", mode: "Szájról olvasás!", points: 2 },
  { word: "szado-mazo bilincs", mode: "Rajzold le!", points: 2 },
  { word: "szado-mazo bilincs", mode: "Szájról olvasás!", points: 2 },
  { word: "hereszopás", mode: "Mutasd meg!", points: 1 },
  { word: "hereszopás", mode: "Szájról olvasás!", points: 2 },
  { word: "izgalomba hoz", mode: "Mutasd meg!", points: 2 },
  { word: "izgalomba hoz", mode: "Szájról olvasás!", points: 2 },
  { word: "egyéjszakás numera", mode: "Magyarázd el!", points: 2 },
  { word: "egyéjszakás numera", mode: "Szájról olvasás!", points: 2 },
  { word: "erotika", mode: "Magyarázd el!", points: 1 },
  { word: "erotika", mode: "Szájról olvasás!", points: 2 },
  { word: "mellszex", mode: "Mutasd meg!", points: 1 },
  { word: "mellszex", mode: "Szájról olvasás!", points: 2 },
  { word: "klitorisz pumpa", mode: "Rajzold le!", points: 3 },
  { word: "klitorisz pumpa", mode: "Szájról olvasás!", points: 2 },
  { word: "elcseppen", mode: "Mutasd meg!", points: 3 },
  { word: "elcseppen", mode: "Szájról olvasás!", points: 2 },
  { word: "nyögdécselés", mode: "Mutasd meg!", points: 2 },
  { word: "nyögdécselés", mode: "Szájról olvasás!", points: 2 },
  { word: "csoportos szex", mode: "Magyarázd el!", points: 1 },
  { word: "csoportos szex", mode: "Szájról olvasás!", points: 2 },
  { word: "spriccelős vibrátor", mode: "Rajzold le!", points: 2 },
  { word: "spriccelős vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "fanszőrzet borotválás", mode: "Rajzold le!", points: 2 },
  { word: "fanszőrzet borotválás", mode: "Szájról olvasás!", points: 2 },
  { word: "szexrandi", mode: "Magyarázd el!", points: 2 },
  { word: "szexrandi", mode: "Szájról olvasás!", points: 2 },
  { word: "hárem", mode: "Rajzold le!", points: 3 },
  { word: "hárem", mode: "Szájról olvasás!", points: 2 },
  { word: "piros lámpás negyed", mode: "Rajzold le!", points: 3 },
  { word: "piros lámpás negyed", mode: "Szájról olvasás!", points: 2 },
  { word: "vagina pumpa", mode: "Rajzold le!", points: 3 },
  { word: "vagina pumpa", mode: "Szájról olvasás!", points: 2 },
  { word: "frigid", mode: "Magyarázd el!", points: 2 },
  { word: "frigid", mode: "Szájról olvasás!", points: 2 },
  { word: "belecsókol a nyakába", mode: "Mutasd meg!", points: 2 },
  { word: "belecsókol a nyakába", mode: "Szájról olvasás!", points: 2 },
  { word: "lovagló póz", mode: "Mutasd meg!", points: 1 },
  { word: "lovagló póz", mode: "Szájról olvasás!", points: 2 },
  { word: "sikítva élvez", mode: "Mutasd meg!", points: 2 },
  { word: "sikítva élvez", mode: "Szájról olvasás!", points: 2 },
  { word: "férfi tanga", mode: "Mutasd meg!", points: 2 },
  { word: "férfi tanga", mode: "Szájról olvasás!", points: 2 },
  { word: "szex party", mode: "Mutasd meg!", points: 2 },
  { word: "szex party", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelmes levél", mode: "Rajzold le!", points: 1 },
  { word: "szerelmes levél", mode: "Szájról olvasás!", points: 2 },
  { word: "cyber vagina", mode: "Magyarázd el!", points: 2 },
  { word: "cyber vagina", mode: "Szájról olvasás!", points: 2 },
  { word: "becéző szavak", mode: "Magyarázd el!", points: 2 },
  { word: "becéző szavak", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelmi vágy", mode: "Magyarázd el!", points: 2 },
  { word: "szerelmi vágy", mode: "Szájról olvasás!", points: 2 },
  { word: "ödipusz komplexus", mode: "Magyarázd el!", points: 3 },
  { word: "ödipusz komplexus", mode: "Szájról olvasás!", points: 2 },
  { word: "a falu kurvája", mode: "Magyarázd el!", points: 2 },
  { word: "a falu kurvája", mode: "Szájról olvasás!", points: 2 },
  { word: "necc ruha", mode: "Rajzold le!", points: 2 },
  { word: "necc ruha", mode: "Szájról olvasás!", points: 2 },
  { word: "lábfetisiszta", mode: "Magyarázd el!", points: 1 },
  { word: "lábfetisiszta", mode: "Szájról olvasás!", points: 2 },
  { word: "érzéki érintés", mode: "Mutasd meg!", points: 2 },
  { word: "érzéki érintés", mode: "Szájról olvasás!", points: 2 },
  { word: "szex rabszolga", mode: "Magyarázd el!", points: 2 },
  { word: "szex rabszolga", mode: "Szájról olvasás!", points: 2 },
  { word: "poligámia", mode: "Magyarázd el!", points: 3 },
  { word: "poligámia", mode: "Szájról olvasás!", points: 2 },
  { word: "szerelmes cirógatás", mode: "Mutasd meg!", points: 2 },
  { word: "szerelmes cirógatás", mode: "Szájról olvasás!", points: 2 },
  { word: "káma szutra", mode: "Rajzold le!", points: 3 },
  { word: "káma szutra", mode: "Szájról olvasás!", points: 2 },
  { word: "genitális ékszer", mode: "Rajzold le!", points: 3 },
  { word: "genitális ékszer", mode: "Szájról olvasás!", points: 2 },
  { word: "masszázsolaj", mode: "Mutasd meg!", points: 2 },
  { word: "masszázsolaj", mode: "Szájról olvasás!", points: 2 },
  { word: "kéjes élvezet", mode: "Mutasd meg!", points: 2 },
  { word: "kéjes élvezet", mode: "Szájról olvasás!", points: 2 },
  { word: "szexuális úton terjedő nemi betegség", mode: "Magyarázd el!", points: 2 },
  { word: "szexuális úton terjedő nemi betegség", mode: "Szájról olvasás!", points: 2 },
  { word: "heteroszexuális", mode: "Magyarázd el!", points: 1 },
  { word: "heteroszexuális", mode: "Szájról olvasás!", points: 2 },
  { word: "mámoros", mode: "Magyarázd el!", points: 2 },
  { word: "mámoros", mode: "Szájról olvasás!", points: 2 },
  { word: "g-pont", mode: "Rajzold le!", points: 3 },
  { word: "g-pont", mode: "Szájról olvasás!", points: 2 },
  { word: "szűzhártya", mode: "Rajzold le!", points: 3 },
  { word: "szűzhártya", mode: "Szájról olvasás!", points: 2 },
  { word: "furulyázás", mode: "Mutasd meg!", points: 1 },
  { word: "furulyázás", mode: "Szájról olvasás!", points: 2 },
  { word: "ondóvezeték", mode: "Rajzold le!", points: 3 },
  { word: "ondóvezeték", mode: "Szájról olvasás!", points: 2 },
  { word: "könnyűvérű nő", mode: "Mutasd meg!", points: 2 },
  { word: "könnyűvérű nő", mode: "Szájról olvasás!", points: 2 },
  { word: "vénuszdomb", mode: "Rajzold le!", points: 3 },
  { word: "vénuszdomb", mode: "Szájról olvasás!", points: 2 },
  { word: "prostituált", mode: "Magyarázd el!", points: 1 },
  { word: "prostituált", mode: "Szájról olvasás!", points: 2 },
  { word: "monogámia", mode: "Magyarázd el!", points: 1 },
  { word: "monogámia", mode: "Szájról olvasás!", points: 2 },
  { word: "mélytorok", mode: "Magyarázd el!", points: 1 },
  { word: "mélytorok", mode: "Szájról olvasás!", points: 2 },
  { word: "elemes vibrátor", mode: "Magyarázd el!", points: 1 },
  { word: "elemes vibrátor", mode: "Szájról olvasás!", points: 2 },
  { word: "orális orgia", mode: "Mutasd meg!", points: 2 },
  { word: "orális orgia", mode: "Szájról olvasás!", points: 2 },
  { word: "plátói szerelem", mode: "Magyarázd el!", points: 2 },
  { word: "plátói szerelem", mode: "Szájról olvasás!", points: 2 },
  { word: "ádámkosztüm", mode: "Mutasd meg!", points: 3 },
  { word: "ádámkosztüm", mode: "Szájról olvasás!", points: 2 },
  { word: "magamutogató", mode: "Mutasd meg!", points: 2 },
  { word: "magamutogató", mode: "Szájról olvasás!", points: 2 },
  { word: "combfix", mode: "Mutasd meg!", points: 1 },
  { word: "combfix", mode: "Szájról olvasás!", points: 2 },
  { word: "nőimitátor", mode: "Mutasd meg!", points: 3 },
  { word: "nőimitátor", mode: "Szájról olvasás!", points: 2 },
  { word: "szendvics álom", mode: "Magyarázd el!", points: 1 },
  { word: "szendvics álom", mode: "Szájról olvasás!", points: 2 },
  { word: "magömlés", mode: "Mutasd meg!", points: 2 },
  { word: "magömlés", mode: "Szájról olvasás!", points: 2 },
  { word: "pornográfia", mode: "Magyarázd el!", points: 1 },
  { word: "pornográfia", mode: "Szájról olvasás!", points: 2 },
  { word: "erotikus álmok", mode: "Magyarázd el!", points: 1 },
  { word: "erotikus álmok", mode: "Szájról olvasás!", points: 2 },
  { word: "nyelvescsók", mode: "Mutasd meg!", points: 1 },
  { word: "nyelvescsók", mode: "Szájról olvasás!", points: 2 },
  { word: "orális izgatás", mode: "Mutasd meg!", points: 2 },
  { word: "orális izgatás", mode: "Szájról olvasás!", points: 2 },
  { word: "összeizzadás", mode: "Magyarázd el!", points: 2 },
  { word: "összeizzadás", mode: "Szájról olvasás!", points: 2 },
  { word: "fityma", mode: "Rajzold le!", points: 2 },
  { word: "fityma", mode: "Szájról olvasás!", points: 2 },
  { word: "korbácsos domina szex", mode: "Mutasd meg!", points: 2 },
  { word: "korbácsos domina szex", mode: "Szájról olvasás!", points: 2 },
  { word: "önkielégítés", mode: "Mutasd meg!", points: 1 },
  { word: "önkielégítés", mode: "Szájról olvasás!", points: 2 },
  { word: "nimfománia", mode: "Magyarázd el!", points: 2 },
  { word: "nimfománia", mode: "Szájról olvasás!", points: 2 },
  { word: "lüktető orgazmus", mode: "Mutasd meg!", points: 3 },
  { word: "lüktető orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "afrodiziákum", mode: "Magyarázd el!", points: 2 },
  { word: "afrodiziákum", mode: "Szájról olvasás!", points: 2 },
  { word: "szatír", mode: "Mutasd meg!", points: 2 },
  { word: "szatír", mode: "Szájról olvasás!", points: 2 },
  { word: "erotikus masszázs", mode: "Mutasd meg!", points: 2 },
  { word: "erotikus masszázs", mode: "Szájról olvasás!", points: 2 },
  { word: "webkamerás szex", mode: "Mutasd meg!", points: 2 },
  { word: "webkamerás szex", mode: "Szájról olvasás!", points: 2 },
  { word: "aktfotó", mode: "Rajzold le!", points: 2 },
  { word: "aktfotó", mode: "Szájról olvasás!", points: 2 },
  { word: "megujjazás", mode: "Mutasd meg!", points: 1 },
  { word: "megujjazás", mode: "Szájról olvasás!", points: 2 },
  { word: "glory hole", mode: "Rajzold le!", points: 2 },
  { word: "glory hole", mode: "Szájról olvasás!", points: 2 },
  { word: "gerjeszt", mode: "Magyarázd el!", points: 2 },
  { word: "gerjeszt", mode: "Szájról olvasás!", points: 2 },
  { word: "pornóújság", mode: "Mutasd meg!", points: 2 },
  { word: "pornóújság", mode: "Szájról olvasás!", points: 2 },
  { word: "bütykös izgató", mode: "Rajzold le!", points: 3 },
  { word: "bütykös izgató", mode: "Szájról olvasás!", points: 2 },
  { word: "cicaruha", mode: "Rajzold le!", points: 2 },
  { word: "cicaruha", mode: "Szájról olvasás!", points: 2 },
  { word: "csikló orgazmus", mode: "Mutasd meg!", points: 2 },
  { word: "csikló orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "szex a tükör előtt", mode: "Rajzold le!", points: 2 },
  { word: "szex a tükör előtt", mode: "Szájról olvasás!", points: 2 },
  { word: "kielégülés", mode: "Mutasd meg!", points: 1 },
  { word: "kielégülés", mode: "Szájról olvasás!", points: 2 },
  { word: "testmasszázs", mode: "Mutasd meg!", points: 2 },
  { word: "testmasszázs", mode: "Szájról olvasás!", points: 2 },
  { word: "domina", mode: "Mutasd meg!", points: 2 },
  { word: "domina", mode: "Szájról olvasás!", points: 2 },
  { word: "péniszgörbület", mode: "Rajzold le!", points: 2 },
  { word: "péniszgörbület", mode: "Szájról olvasás!", points: 2 },
  { word: "kiszívja a nyakát", mode: "Magyarázd el!", points: 2 },
  { word: "kiszívja a nyakát", mode: "Szájról olvasás!", points: 2 },
  { word: "szexuális álmok", mode: "Magyarázd el!", points: 1 },
  { word: "szexuális álmok", mode: "Szájról olvasás!", points: 2 },
  { word: "latex imádó", mode: "Magyarázd el!", points: 2 },
  { word: "latex imádó", mode: "Szájról olvasás!", points: 2 },
  { word: "mellbimbótekeréssel fájdalomokozás", mode: "Mutasd meg!", points: 2 },
  { word: "mellbimbótekeréssel fájdalomokozás", mode: "Szájról olvasás!", points: 2 },
  { word: "bigámia", mode: "Magyarázd el!", points: 2 },
  { word: "bigámia", mode: "Szájról olvasás!", points: 2 },
  { word: "beindít", mode: "Mutasd meg!", points: 2 },
  { word: "beindít", mode: "Szájról olvasás!", points: 2 },
  { word: "érzékenység", mode: "Magyarázd el!", points: 1 },
  { word: "érzékenység", mode: "Szájról olvasás!", points: 2 },
  { word: "anális élvezet", mode: "Mutasd meg!", points: 2 },
  { word: "anális élvezet", mode: "Szájról olvasás!", points: 2 },
  { word: "paskolás", mode: "Mutasd meg!", points: 1 },
  { word: "paskolás", mode: "Szájról olvasás!", points: 2 },
  { word: "genitális szagok", mode: "Rajzold le!", points: 2 },
  { word: "genitális szagok", mode: "Szájról olvasás!", points: 2 },
  { word: "tapadókorongos pénisz", mode: "Rajzold le!", points: 3 },
  { word: "tapadókorongos pénisz", mode: "Szájról olvasás!", points: 2 },
  { word: "orgazmus", mode: "Mutasd meg!", points: 1 },
  { word: "orgazmus", mode: "Szájról olvasás!", points: 2 },
  { word: "pezsgőfürdős szex", mode: "Mutasd meg!", points: 3 },
  { word: "pezsgőfürdős szex", mode: "Szájról olvasás!", points: 2 },
  { word: "orális szex", mode: "Mutasd meg!", points: 1 },
  { word: "orális szex", mode: "Szájról olvasás!", points: 2 },
  { word: "szex a konyhában", mode: "Mutasd meg!", points: 2 },
  { word: "szex a konyhában", mode: "Szájról olvasás!", points: 2 },
  { word: "szex az autóban", mode: "Mutasd meg!", points: 2 },
  { word: "szex az autóban", mode: "Szájról olvasás!", points: 2 },
  { word: "latex fejmaszk", mode: "Rajzold le!", points: 3 },
  { word: "latex fejmaszk", mode: "Szájról olvasás!", points: 2 },
  { word: "méteres kékeres", mode: "Rajzold le!", points: 2 },
  { word: "méteres kékeres", mode: "Szájról olvasás!", points: 2 },
];
